### ISSUE TITLE
Consider adding Fireward

### ISSUE THREAD

**Issue by bijoutrouvaille** [jthegedus/awesome-firebase#15]
https://github.com/bijoutrouvaille/fireward

It's a Bolt-like language for Firestore to make rule writing much easier. Also generates a TypeScript file with typings.

**Comment by jthegedus** [comment]
Thanks @bijoutrouvaille! Please consider https://github.com/jthegedus/awesome-firebase/issues/2

**Comment by bijoutrouvaille** [comment]
But of course!
